apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-app-deployment-controller
  labels:
    app: redis-controller
    type: back-end
spec:
  template:
    metadata:
      name: redis-app
      labels:
        app: redis-app
        type: back-end
    spec:
      containers:
        - name: redis-app
          image: redis:alpine
  replicas: 1
  selector:
    matchLabels:
      app: redis-app
      type: back-end
      
