apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment-controller
  labels:
    app: myapp
    type: back-end
spec:
  template:
    metadata:
      name: nginx
      labels:
        app: myapp-deployment
        type: back-end
    spec:
      containers:
        - name: nginx
          image: nginx

  replicas: 3
  selector:
    matchLabels:
      app: myapp-deployment
      type: back-end
      
