apiVersion: v1
kind: Service
metadata:
  name: result
spec:
  type: NodePort
  ports:
    - name: result-service
      targetPort: 80
      port: 8080
      nodePort: 31001
  selector:
    app: result-app
    type: front-end