apiVersion: v1
kind: Service
metadata:
  name: result
spec:
# when in cloud, use LoadBalancer instead of NodePort
  type: LoadBalancer
  ports:
    - name: result-service
      targetPort: 80
      port: 8080
      nodePort: 31001
  selector:
    app: result-app
    type: front-end